set(CPACK_RPM_PACKAGE_VERSION ${PROJECT_VERSION})

set(CPACK_RPM_PACKAGE_AUTOREQ 1)
set(CPACK_RPM_PACKAGE_AUTOPROV 1)

set(CPACK_RPM_COMPONENT_INSTALL ON)

set(CPACK_RPM_APPIMAGE_CLI_TOOL_PACKAGE_NAME appimage-cli-tool)

set(CPACK_RPM_APPIMAGE_CLI_TOOL_FILE_NAME RPM-DEFAULT)
